name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  PROJECT_ID: notional-zephyr-229707
  GAR_LOCATION: asia-east1
  REPOSITORY: demo-registry
  IMAGE: cicd-demo-image

jobs:
  build-image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Docker build'
      run: |
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}" .

    - name: 'Docker login'
      uses: docker/login-action@v3
      with:
        registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: 'Docker push'
      run: |
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}"
